config/routes.rb
TravelApp::Application.routes.draw do  # The priority is based upon order of creation: first created -> highest priority.
  
  root 'dato_entidads#home'
  
  resources :regions
  resources :menus
  resources :accions
  resources :modelos
    
  resources :division_territorials
  resources :division_territorial_pais
  get 'entidad_territorials/actualizar_controles_dependientes' => 'entidad_territorials#actualizar_controles_dependientes', as: :actualizar_controles_dependientes
  
  concern :image_attachable do
    resources :fotos, only: :new
  end
  
  resources :paquete_turisticos, concerns: :image_attachable 
  resources :entidad_territorials, concerns: :image_attachable 
  
  
  
  resources :fotos
  
  resources :parametro_sistemas
  
  get 'dato_entidads/home' => 'dato_entidads#home', as: :home
  get 'dato_entidads/contactenos' => 'dato_entidads#contactenos'
  get 'dato_entidads/somos' => 'dato_entidads#somos'
  resources :dato_entidads
  
  
  resources :perfils do
    get '/perfils/:perlfil_id/permisos/new' => 'permisos#new'
    resources :permisos   
  end
  
  resources :permisos 
  
  resources :controls
  
  get 'funcion_controls/actualizar_controles_por_tipo' => 'funcion_controls#actualizar_controles_por_tipo', as: :actualizar_controles_por_tipo
  
  resources :funcion_controls
  
  resources :funcionalidads do
    resources :funcion_controls
  end
  
  get 'catalogos/actualizar_subcategorias' => 'catalogos#actualizar_subcategorias', as: :actualizar_subcategorias
  resources :catalogos
  
  
  get 'usuarios/cerrar_sesion' => 'usuarios#cerrar_sesion' , as: :cerrar_sesion
  get 'usuarios/iniciar_sesion' => 'usuarios#iniciar_sesion' , as: :iniciar_sesion
  post 'usuarios/change_password' => 'usuarios#change_password', as: :change_password
  get 'usuarios/new_password' => 'usuarios#new_password', as: :new_password
  get 'usuarios/login' => 'usuarios#login', as: :login
  post 'usuarios/login_attempt' => 'usuarios#login_attempt', as: :login_attempt
  resources :usuarios
  
    

  

end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
  validates :ctlg_categoria, presence: {message: "=> Es un dato requerido"}, length: { in: 5..100, too_short: "=> La categoria debe tener entre 5 y 100 caracteres", too_long:"=> La categoria debe tener entre 5 y 100 caracteres"}
  validates :ctlg_subcategoria, length: { in: 0..100, too_short: "=> La subcategoria debe tener entre 0 y 100 caracteres", too_long:"=> La subcategoria debe tener entre 0 y 100 caracteres"}
  validates :ctlg_valor_cdg, presence: {message: "=> Es un dato reuqerido"}, length: { in: 1..20, too_short: "=> El codigo debe tener entre 1 y 20 caracteres", too_long: "=> El codigo debe tener entre 1 y 20 caracteres"}
  validates :ctlg_estado_registro, presence: {message: "=> Es un dato requerido"}, length: { is: 1 }, inclusion: { in: %w(A E), message: "=> %{value} no es un estado valido" } 
end

app/controllers/catalogos_controller.rb
class CatalogosController < ApplicationController
  include ApplicationHelper
  
  before_action :set_catalogo, only: [:show, :edit, :update, :destroy]
  before_action :set_estado_registro, only: [:show, :edit]
  before_action :set_datos_basicos, only: [:index, :edit, :new, :create]
  
  # GET /catalogos
  # GET /catalogos.json
  def index
    #@categorias = Catalogo.select("ctlg_categoria").distinct.where("ctlg_categoria IS NOT NULL")
    #@subcategorias = Catalogo.select("ctlg_subcategoria").distinct.where("ctlg_subcategoria IS NOT NULL")
    
    condiciones = []
    cadena = "ctlg_estado_registro = 'A'"
    
    @catalogo = Catalogo.new(catalogo_params)

    unless @catalogo.ctlg_categoria.blank? then
      condiciones.push("Upper(ctlg_categoria) = '#{@catalogo.ctlg_categoria.to_s.upcase}'")
    end
    
    unless @catalogo.ctlg_subcategoria.blank? then
      condiciones.push("Upper(ctlg_subcategoria) = '#{@catalogo.ctlg_subcategoria.to_s.upcase}'")
    end
    
    unless @catalogo.ctlg_valor_desc.blank? then
      condiciones.push("Upper(ctlg_valor_desc) LIKE '%#{@catalogo.ctlg_valor_desc.to_s.upcase}%'")
    end    
    
    if condiciones.any? then
      condiciones.each do |condicion|
        if condicion != nil then
            cadena = cadena + " AND " + condicion.to_s
        end
      end
      
      @catalogos = Catalogo.select('id, ctlg_categoria, ctlg_subcategoria, ctlg_valor_cdg, ctlg_valor_desc, ctlg_observacion, ctlg_estado_registro').where(cadena).limit(100)
    else
      @catalogos = Catalogo.none
    end
    
  end

  # GET /catalogos/1
  # GET /catalogos/1.json
  def show
  end

  # GET /catalogos/new
  def new
    @catalogo = Catalogo.new
    @catalogo.ctlg_estado_registro = "A"
  end

  # GET /catalogos/1/edit
  def edit
  end

  # POST /catalogos
  # POST /catalogos.json
  def create
    @catalogo = Catalogo.new(catalogo_params)
    respond_to do |format|
      if @catalogo.save
        format.html { redirect_to @catalogo, notice: 'Registro creado exitosamente.' }
        format.json { render action: 'show', status: :created, location: @catalogo }
      else
        format.html { render action: 'new' }
        format.json { render json: @catalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogos/1
  # PATCH/PUT /catalogos/1.json
  def update
    respond_to do |format|
      if @catalogo.update(catalogo_params)
        format.html { redirect_to @catalogo, notice: 'Registro actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @catalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogos/1
  # DELETE /catalogos/1.json
  def destroy
    @catalogo.destroy
    respond_to do |format|
      format.html { redirect_to catalogos_url }
      format.json { head :no_content }
    end
  end

    def set_estado_registro
      @catalogo.ctlg_estado_registro = set_estado_registro_actual(@catalogo.ctlg_estado_registro, action_name)
    end

  private
    def set_datos_basicos
      set_estados_registro # todos los estados de registro
      @categorias = Catalogo.select("ctlg_categoria").distinct.where("ctlg_categoria IS NOT NULL")
      @subcategorias = Catalogo.select("ctlg_subcategoria").distinct.where("ctlg_subcategoria IS NOT NULL")
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_catalogo
      @catalogo = Catalogo.find(params[:id])
      
      if action_name == "show" and @catalogo.ctlg_subcategoria.blank? then
        @catalogo.ctlg_subcategoria = "NINGUNA"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalogo_params
      #params.require(:catalogo).permit(:ctlg_categoria, :ctlg_subcategoria, :ctlg_valor_cdg, :ctlg_valor_desc, :ctlg_observacion, :ctlg_estado_registro)
      params.fetch(:catalogo, {}).permit(:ctlg_categoria, :ctlg_subcategoria, :ctlg_valor_cdg, :ctlg_valor_desc, :ctlg_observacion, :ctlg_estado_registro)
    end
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/views/catalogos/_form.html.erb
  <script>
  $(function() {
    var categorias = [
    <% if @categorias != nil %>
    <% @categorias.each do |categoria| %>
      	{
      	
        	value: "<%= categoria.ctlg_categoria %>",
        	label: "<%= categoria.ctlg_categoria %>",
        	desc: "",
        	icon: ""
      },
    <% end %>
    <% end %>
    ];
    
    var subcategorias = [
    <% @subcategorias.each do |subcategoria| %>
      	{
      	
        	value: "<%= subcategoria.ctlg_subcategoria %>",
        	label: "<%= subcategoria.ctlg_subcategoria %>",
        	desc: "",
        	icon: ""
      },
    <% end %>
    ];
    
    $( "#catalogo_ctlg_categoria" ).autocomplete({
      minLength: 0,
      source: categorias,
      focus: function( event, ui ) {
        $( "#catalogo_ctlg_categoria" ).val( ui.item.label );
        return false;
      },
      select: function( event, ui ) {
        $( "#catalogo_ctlg_categoria" ).val( ui.item.value );
        return false;
      }
    })
    /**************************************************/
     $( "#catalogo_ctlg_subcategoria" ).autocomplete({
      minLength: 0,
      source: subcategorias,
      focus: function( event, ui ) {
        $( "#catalogo_ctlg_subcategoria" ).val( ui.item.label );
        return false;
      },
      select: function( event, ui ) {
        $( "#catalogo_ctlg_subcategoria" ).val( ui.item.value );
        return false;
      }
    })
    .data( "ui-autocomplete" )._renderItem = function( ul, item ) {
      return $( "<li>" )
        .append( "<a>" + item.label + "<br>" + item.desc + "</a>" )
        .appendTo( ul );
    };
  });
  </script>
<style>
  .custom-combobox {
    position: relative;
    display: inline-block;
  }
  .custom-combobox-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -1px;
    padding: 0;
    /* support: IE7 */
    *height: 1.7em;
    *top: 0.1em;
  }
  .custom-combobox-input {
    margin: 0;
    padding: 0.3em;
  }
  </style>
  <script>
  (function( $ ) {
    $.widget( "custom.combobox", {
      _create: function() {
        this.wrapper = $( "<span>" )
          .addClass( "custom-combobox" )
          .insertAfter( this.element );
 
        this.element.hide();
        this._createAutocomplete();
        this._createShowAllButton();
      },
 
      _createAutocomplete: function() {
        var selected = this.element.children( ":selected" ),
          value = selected.val() ? selected.text() : "";
 
        this.input = $( "<input>" )
          .appendTo( this.wrapper )
          .val( value )
          .attr( "title", "" )
          .addClass( "custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
          .autocomplete({
            delay: 0,
            minLength: 0,
            source: $.proxy( this, "_source" )
          })
          .tooltip({
            tooltipClass: "ui-state-highlight"
          });
 
        this._on( this.input, {
          autocompleteselect: function( event, ui ) {
            ui.item.option.selected = true;
            this._trigger( "select", event, {
              item: ui.item.option
            });
          },
 
          autocompletechange: "_removeIfInvalid"
        });
      },
 
      _createShowAllButton: function() {
        var input = this.input,
          wasOpen = false;
 
        $( "<a>" )
          .attr( "tabIndex", -1 )
          //.attr( "title", "Mostrar todas las opciones" )
          .tooltip()
          .appendTo( this.wrapper )
          .button({
            icons: {
              primary: "ui-icon-triangle-1-s"
            },
            text: false
          })
          .removeClass( "ui-corner-all" )
          .addClass( "custom-combobox-toggle ui-corner-right" )
          .mousedown(function() {
            wasOpen = input.autocomplete( "widget" ).is( ":visible" );
          })
          .click(function() {
            input.focus();
 
            // Close if already visible
            if ( wasOpen ) {
              return;
            }
 
            // Pass empty string as value to search for, displaying all results
            input.autocomplete( "search", "" );
          });
      },
 
      _source: function( request, response ) {
        var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
        response( this.element.children( "option" ).map(function() {
          var text = $( this ).text();
          if ( this.value && ( !request.term || matcher.test(text) ) )
            return {
              label: text,
              value: text,
              option: this
            };
        }) );
      },
 
      _removeIfInvalid: function( event, ui ) {
 
        // Selected an item, nothing to do
        if ( ui.item ) {
          return;
        }
 
        // Search for a match (case-insensitive)
        var value = this.input.val(),
          valueLowerCase = value.toLowerCase(),
          valid = false;
        this.element.children( "option" ).each(function() {
          if ( $( this ).text().toLowerCase() === valueLowerCase ) {
            this.selected = valid = true;
            return false;
          }
        });
 
        // Found a match, nothing to do
        if ( valid ) {
          return;
        }
 
        // Remove invalid value
        this.input
          .val( "" )
          .attr( "title", value + " no es una opción válida" )
          .tooltip( "open" );
        this.element.val( "" );
        this._delay(function() {
          this.input.tooltip( "close" ).attr( "title", "" );
        }, 2500 );
        this.input.data( "ui-autocomplete" ).term = "";
      },
 
      _destroy: function() {
        this.wrapper.remove();
        this.element.show();
      }
    });
  })( jQuery );
  </script>
<script>
   $(function() {
    $( "#catalogo_ctlg_estado_registro" ).combobox();
  });
  </script>

<%= form_for(@catalogo) do |f| %>
	<% if @catalogo.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@catalogo.errors.count, "error", "errores") %> no permite(n) que este registro sea grabado:</h2>
      		<ul>
      			<% @catalogo.errors.full_messages.each do |msg| %>
        			<li><%= msg %></li>
      			<% end %>
      		</ul>
    	</div>
  	<% end %>
	<div class = "form_fields">
  		<div class="field">
    		<%= f.label :Categoria, "Categoría *" %><br>
    		<%= f.text_field :ctlg_categoria, options= {size:50, maxlength:40, required: :required, autofocus: :autofocus, "data-validation" => "length alphanumeric", "data-validation-allowing" =>" ", "data-validation-length" => "min5"} %>
  		</div>
	  	<div class="field">
	    	<%= f.label :Subcategoría %><br>
	    	<%= f.text_field :ctlg_subcategoria, options= {size:50, maxlength:40, "data-validation" => "alphanumeric length", "data-validation-length" => "min5", "data-validation-optional" => "true" } %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :Código, "Código *" %><br>
	    	<%= f.text_field :ctlg_valor_cdg , options= {size:50, maxlength:40, required: :required, "data-validation" => "length alphanumeric", "data-validation-length" => "min3"}%>
	  	</div>
	  	<div class="field">
	    	<%= f.label :Descripción, "Descripción *" %><br>
	    	<%= f.text_field :ctlg_valor_desc, options= {size:50, maxlength:40, required: :required, "data-validation" => "length alphanumeric", "data-validation-allowing" =>" ", "data-validation-length" => "min5"} %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :Observación %><br>
	    	<%= f.text_field :ctlg_observacion, options= {size:50, maxlength:40, "data-validation" => "length alphanumeric", "data-validation-length" => "min5", "data-validation-optional" => "true" } %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :Estado_registro, "Estado registro *" %><br>
	    	<%= f.select :ctlg_estado_registro, @estados_registro.map{|u| [u.ctlg_valor_desc, u.ctlg_valor_cdg]}.insert(nil.to_f, nil), selected: @catalogo.ctlg_estado_registro %>
	  	</div>
  	</div>
  	<div class="bottom">
  		<div class="actions">
			<% if action_name == "edit"%>
				<%= f.submit "Aceptar", class: "cmd save", id: :cmd_aceptar %> |
				<%= link_to 'Consultar', @perfil, class: "cmd star", id: :cmd_consultar %> |
			<% elsif action_name == "new" or action_name =="create" %>
				<script>
					$(function(){
						$("#cmd_aceptar")
						.click(function(){
							$('#new_catalogo').submit();
						});
					});
				</script>
				
				<%= link_to "Aceptar", nil, class: "cmd save", id: :cmd_aceptar %> |
			<% end %>
			<%= link_to 'Regresar', catalogos_path, class: "cmd previous", id: :cmd_regresar %>
  		</div>
  	</div>
<% end %>
<script> $.validate(); </script>

app/views/catalogos/actualizar_subcategorias.js.erb
<% @subcategorias = Catalogo.select("ctlg_subcategoria").distinct.where("ctlg_categoria = '#{params[:ctlg_categoria]}' AND ctlg_subcategoria IS NOT NULL ").map{|a| [a.ctlg_subcategoria, a.ctlg_subcategoria]}.insert(nil.to_f, nil) %>
$('#catalogo_ctlg_subcategoria').empty(); 
$('#catalogo_ctlg_subcategoria').html("<%= escape_javascript(options_for_select(@subcategorias)) %>");

app/views/catalogos/edit.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Modificar registro</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-->

app/views/catalogos/index.html.erb
<style>
  .custom-combobox {
    position: relative;
    display: inline-block;
  }
  .custom-combobox-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -1px;
    padding: 0;
    /* support: IE7 */
    *height: 1.7em;
    *top: 0.1em;
  }
  .custom-combobox-input {
  	
  	font-size:12px;
    margin: 0;
    padding: 0.3em;
    width: 20em;
  }
  </style>
  <script>
  (function( $ ) {
    $.widget( "custom.combobox", {
      _create: function() {
        this.wrapper = $( "<span>" )
          .addClass( "custom-combobox" )
          .insertAfter( this.element );
 
        this.element.hide();
        this._createAutocomplete();
        this._createShowAllButton();
      },
 
      _createAutocomplete: function() {
        var selected = this.element.children( ":selected" ),
          value = selected.val() ? selected.text() : "";
 
        this.input = $( "<input>" )
          .appendTo( this.wrapper )
          .val( value )
          .attr( "title", "" )
          .addClass( "custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
          .autocomplete({
            delay: 0,
            minLength: 0,
            source: $.proxy( this, "_source" )
          })
          .tooltip({
            tooltipClass: "ui-state-highlight"
          });
 
        this._on( this.input, {
          autocompleteselect: function( event, ui ) {
            ui.item.option.selected = true;
            this._trigger( "select", event, {
              item: ui.item.option
            });
          },
 
          autocompletechange: "_removeIfInvalid"
        });
      },
 
      _createShowAllButton: function() {
        var input = this.input,
          wasOpen = false;
 
        $( "<a>" )
          .attr( "tabIndex", -1 )
          //.attr( "title", "Mostrar todas las opciones" )
          .tooltip()
          .appendTo( this.wrapper )
          .button({
            icons: {
              primary: "ui-icon-triangle-1-s"
            },
            text: false
          })
          .removeClass( "ui-corner-all" )
          .addClass( "custom-combobox-toggle ui-corner-right" )
          .mousedown(function() {
            wasOpen = input.autocomplete( "widget" ).is( ":visible" );
          })
          .click(function() {
            input.focus();
 
            // Close if already visible
            if ( wasOpen ) {
              return;
            }
 
            // Pass empty string as value to search for, displaying all results
            input.autocomplete( "search", "" );
          });
      },
 
      _source: function( request, response ) {
        var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
        response( this.element.children( "option" ).map(function() {
          var text = $( this ).text();
          if ( this.value && ( !request.term || matcher.test(text) ) )
            return {
              label: text,
              value: text,
              option: this
            };
        }) );
      },
 
      _removeIfInvalid: function( event, ui ) {
 
        // Selected an item, nothing to do
        if ( ui.item ) {
	      	$.ajax({
					url: "<%= actualizar_subcategorias_path %>",
					data: {
  							ctlg_categoria : $('#catalogo_ctlg_categoria').val()
						  },
					dataType: "script"
		 });
          return;
        }
 
        // Search for a match (case-insensitive)
        var value = this.input.val(),
          valueLowerCase = value.toLowerCase(),
          valid = false;
        this.element.children( "option" ).each(function() {
          if ( $( this ).text().toLowerCase() === valueLowerCase ) {
            this.selected = valid = true;
            return false;
          }
        });
 
        // Found a match, nothing to do
        if ( valid ) {
        	
	      	$.ajax({
					url: "<%= actualizar_subcategorias_path %>",
					data: {
  							ctlg_categoria : $('#catalogo_ctlg_categoria').val()
						  },
					dataType: "script"
		 });
          return;
        }
 
        // Remove invalid value
        this.input
          .val( "" )
          .attr( "title", value + " no es una opción válida" )
          .tooltip( "open" );
        this.element.val( "" );
        this._delay(function() {
          this.input.tooltip( "close" ).attr( "title", "" );
        }, 2500 );
        this.input.data( "ui-autocomplete" ).term = "";
      },
 
      _destroy: function() {
        this.wrapper.remove();
        this.element.show();
      }
    });
  })( jQuery );
  </script>
<script>
   $(function() {
    $( "#catalogo_ctlg_categoria" ).combobox();
    $( "#toggle" ).click(function() {
      $( "#catalogo_ctlg_categoria" ).toggle();
    });
  });
  $(function() {
    $( "#catalogo_ctlg_subcategoria" ).combobox();
    $( "#toggle" ).click(function() {
      $( "#catalogo_ctlg_subcategoria" ).toggle();
    });
  });
  </script>
<script>
$(document).ready(function() {
    $('#table_index').dataTable( {
    	"bJQueryUI": true,
        "sPaginationType": "full_numbers"
    } );
} );
</script>
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Cat&aacute;logos</h3>
			<br/>
			<div class="form buscar">
				<%= form_tag catalogos_path, method: 'get' do %>
					<table width="100%">
						<tr>
							<td>
								&nbsp;&nbsp;&nbsp;
  								<%= label_tag(:ctlg_categoria, "Categoría") %>&nbsp;&nbsp;&nbsp;
  								<%= collection_select(:catalogo, :ctlg_categoria, @categorias, :ctlg_categoria, :ctlg_categoria, :prompt => '') %>
  								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  								<%= label_tag(:ctlg_subcategoria, "Subcategoría") %>&nbsp;
  								<%= select(:catalogo, :ctlg_subcategoria, []) %>
  								<%= submit_tag "Buscar" %>
  						</td>
  						</tr>
  						<tr>
  							<td>
  						&nbsp;&nbsp;&nbsp;
  						<%= label_tag(:ctlg_valor_desc, "Descripción") %>&nbsp;
  						<%= text_field(:catalogo, :ctlg_valor_desc, size:40) %>
  						</td>
  						</tr>  
  						
 				 	</table>
				<% end %>
</div>

	<center>

<table id="table_index">
  <thead>
    <tr>
      <th>Categor&iacute;a</th>
      <th>Subcategor&iacute;a</th>
      <!-- <th width="5%">Codigo</th> -->
      <th>Descripci&oacute;n</th>
      <!--th>Observaci&oacute;n</th-->
      <th>Estado registro</th>
      <th width="10%"></th>
      <th width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @catalogos.each do |catalogo| %>
      <tr>
        <td><%= catalogo.ctlg_categoria %></td>
        <td><%= catalogo.ctlg_subcategoria %></td>
        <!--td><%#= catalogo.ctlg_valor_cdg %></td-->
        <td><%= link_to catalogo.ctlg_valor_desc, catalogo %></td>
        <!--td><%= catalogo.ctlg_observacion %></td-->
        <td><%= catalogo.ctlg_estado_registro %></td>
        <td><%= link_to 'Editar', edit_catalogo_path(catalogo), class: "cmd edit", id: :cmd_editar %></td>
        <td><%= link_to 'Borrar', catalogo, method: :delete, data: { confirm: '¿Está seguro de eliminar este registro?' } , class: "cmd delete", id: :cmd_borrar %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<!--/div-->

<div class="bottom">
<%= link_to 'Crear catálogo', new_catalogo_path, class: "cmd add", id: :cmd_crear %>
</div>

</div>
</div>
</div>

app/views/catalogos/new.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Nuevo registro</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	

app/views/catalogos/show.html.erb
<% if notice != nil then %>
	<div class="notibox success">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Cat&aacute;logo</h3>
			<div class="form">
				<div class = "form_fields">
					<table>
						<tbody>
							<tr>
						  		<td><strong>Categoria:</strong></td>
						  		<td><%= @catalogo.ctlg_categoria %></td>
							</tr>
							<tr>
						  		<td><strong>Subcategoria:</strong></td>
						  		<td><%= @catalogo.ctlg_subcategoria %></td>
							</tr>
							<tr>
						  		<td><strong>C&oacute;digo</strong></td>
						  		<td><%= @catalogo.ctlg_valor_cdg %></td>
							</tr>
							<tr>
						  		<td><strong>Descripci&oacute;n:</strong></td>
						  		<td><%= @catalogo.ctlg_valor_desc %></td>
							</tr>
							<tr>
						  		<td><strong>Observaci&oacute;n:</strong></td>
						  		<td><%= @catalogo.ctlg_observacion %></td>
							</tr>
							<tr>
						  		<td><strong>Estado registro:</strong></td>
						  		<td><%= @catalogo.ctlg_estado_registro %></td>
						  	</tr>
					  	</tbody>
					</table>
				</div>
			</div>
			<div class="bottom">
				<%= link_to 'Editar', edit_catalogo_path(@catalogo), class: "cmd edit", id: :cmd_editar %> |
				<%= link_to 'Regresar', catalogos_path, class: "cmd previous", id: :cmd_regresar %>
			</div>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	