config/routes.rb
TravelApp::Application.routes.draw do  # The priority is based upon order of creation: first created -> highest priority.
  
  root 'dato_entidads#home'
  
  resources :regions
  resources :menus
  resources :accions
  resources :modelos
    
  resources :division_territorials
  resources :division_territorial_pais
  get 'entidad_territorials/actualizar_controles_dependientes' => 'entidad_territorials#actualizar_controles_dependientes', as: :actualizar_controles_dependientes
  
  concern :image_attachable do
    resources :fotos, only: :new
  end
  
  resources :paquete_turisticos, concerns: :image_attachable 
  resources :entidad_territorials, concerns: :image_attachable 
  
  
  
  resources :fotos
  
  resources :parametro_sistemas
  
  get 'dato_entidads/home' => 'dato_entidads#home', as: :home
  get 'dato_entidads/contactenos' => 'dato_entidads#contactenos'
  get 'dato_entidads/somos' => 'dato_entidads#somos'
  resources :dato_entidads
  
  
  resources :perfils do
    get '/perfils/:perlfil_id/permisos/new' => 'permisos#new'
    resources :permisos   
  end
  
  resources :permisos 
  
  resources :controls
  
  get 'funcion_controls/actualizar_controles_por_tipo' => 'funcion_controls#actualizar_controles_por_tipo', as: :actualizar_controles_por_tipo
  
  resources :funcion_controls
  
  resources :funcionalidads do
    resources :funcion_controls
  end
  
  get 'catalogos/actualizar_subcategorias' => 'catalogos#actualizar_subcategorias', as: :actualizar_subcategorias
  resources :catalogos
  
  
  get 'usuarios/cerrar_sesion' => 'usuarios#cerrar_sesion' , as: :cerrar_sesion
  get 'usuarios/iniciar_sesion' => 'usuarios#iniciar_sesion' , as: :iniciar_sesion
  post 'usuarios/change_password' => 'usuarios#change_password', as: :change_password
  get 'usuarios/new_password' => 'usuarios#new_password', as: :new_password
  get 'usuarios/login' => 'usuarios#login', as: :login
  post 'usuarios/login_attempt' => 'usuarios#login_attempt', as: :login_attempt
  resources :usuarios
  
    

  

end

app/models/funcion_control.rb
class FuncionControl < ActiveRecord::Base
  # belongs_to :funcionalidad
  # belongs_to :modelo
  # belongs_to :accion
  # belongs_to :control
end

app/controllers/funcion_controls_controller.rb
class FuncionControlsController < ApplicationController
  before_action :set_funcion_control, only: [:show, :edit, :update, :destroy]

  # GET /funcion_controls
  # GET /funcion_controls.json
  def index
    @funcion_controls = FuncionControl.all
  end

  # GET /funcion_controls/1
  # GET /funcion_controls/1.json
  def show
    @funcionalidad = Funcionalidad.find(params[:funcionalidad_id])
  end

  # GET /funcion_controls/new
  def new
    @funcionalidad_funcion_control = FuncionControl.new
    @funcionalidad = Funcionalidad.find(params[:funcionalidad_id])
    @modelos = Modelo.where("mdl_estado_registro = 'A'").order(mdl_nombre: :asc)
    @acciones = Accion.all.order(acc_nombre: :asc)
    @tipos_control = Catalogo.select("ctlg_valor_desc descripcion, ctlg_valor_cdg codigo").where("ctlg_categoria='APLICACION' AND ctlg_subcategoria = 'TIPO DE CONTROL'").order(ctlg_valor_desc: :asc)
  end

  # GET /funcion_controls/1/edit
  def edit
    @funcionalidad_funcion_control = @funcion_control
    @funcionalidad = Funcionalidad.find(@funcion_control.funcionalidad_id)
    @modelos = Modelo.all.order(mdl_nombre: :asc)
    @acciones = Accion.all
    @tipos_control = Catalogo.select("ctlg_valor_desc descripcion, ctlg_valor_cdg codigo").where("ctlg_categoria='APLICACION' AND ctlg_subcategoria = 'TIPO DE CONTROL'").order(ctlg_valor_desc: :asc)
    control = Control.find(@funcion_control.control_id)
    
    #El combo de controles se llena con los controles del mismo tipo del actual
    @controles = Control.where("ctrl_tipo = '#{control.ctrl_tipo}'")
  end

  # POST /funcion_controls
  # POST /funcion_controls.json
  def create
    @funcion_control = FuncionControl.new(funcion_control_params)
    @funcionalidad = Funcionalidad.find(@funcion_control.funcionalidad_id)
    
    respond_to do |format|
      if @funcion_control.save
        format.html { redirect_to funcionalidad_funcion_control_path(@funcionalidad, @funcion_control), notice: 'Registro creado exitosamente.' }
        #format.json { render action: 'show', status: :created, location: @funcion_control }
        
      else
        format.html { render action: 'new' }
        format.json { render json: @funcion_control.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcion_controls/1
  # PATCH/PUT /funcion_controls/1.json
  def update
    
    @fc = FuncionControl.new(funcion_control_params)
    @funcionalidad = Funcionalidad.find(@fc.funcionalidad_id)
    
    respond_to do |format|
      if @funcion_control.update(funcion_control_params)
        format.html { redirect_to funcionalidad_funcion_control_path(@funcionalidad, @funcion_control), notice: 'Registro actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @funcion_control.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcion_controls/1
  # DELETE /funcion_controls/1.json
  def destroy
    @funcionalidad = Funcionalidad.find(@funcion_control.funcionalidad_id)
    @funcion_control.destroy
    respond_to do |format|
      #format.html { redirect_to funcion_controls_url }
      format.html { redirect_to edit_funcionalidad_path(@funcionalidad) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcion_control
      @funcion_control = FuncionControl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcion_control_params
      params.require(:funcion_control).permit(:funcionalidad_id, :modelo_id, :accion_id, :control_id)
    end
end

app/helpers/funcion_controls_helper.rb
module FuncionControlsHelper
end

app/views/funcion_controls/_form.html.erb
<style>
  .custom-combobox {
    position: relative;
    display: inline-block;
  }
  .custom-combobox-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -1px;
    padding: 0;
    /* support: IE7 */
    *height: 1.7em;
    *top: 0.1em;
  }
  .custom-combobox-input {
    margin: 0;
    padding: 0.3em;
  }
  </style>
<script>
 (function( $ ) {
    $.widget( "custom.combobox", {
      _create: function() {
        this.wrapper = $( "<span>" )
          .addClass( "custom-combobox" )
          .insertAfter( this.element );
 
        this.element.hide();
        this._createAutocomplete();
        this._createShowAllButton();
      },
 
      _createAutocomplete: function() {
        var selected = this.element.children( ":selected" ),
          value = selected.val() ? selected.text() : "";
 
        this.input = $( "<input>" )
          .appendTo( this.wrapper )
          .val( value )
          .attr( "title", "" )
          .addClass( "custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
          .autocomplete({
            delay: 0,
            minLength: 0,
            source: $.proxy( this, "_source" )
          })
          .tooltip({
            tooltipClass: "ui-state-highlight"
          });
 
        this._on( this.input, {
          autocompleteselect: function( event, ui ) {
            ui.item.option.selected = true;
            this._trigger( "select", event, {
              item: ui.item.option
            });
          },
 
          autocompletechange: "_removeIfInvalid"
        });
      },
 
      _createShowAllButton: function() {
        var input = this.input,
          wasOpen = false;
 
        $( "<a>" )
          .attr( "tabIndex", -1 )
          //.attr( "title", "Mostrar todas las opciones" )
          .tooltip()
          .appendTo( this.wrapper )
          .button({
            icons: {
              primary: "ui-icon-triangle-1-s"
            },
            text: false
          })
          .removeClass( "ui-corner-all" )
          .addClass( "custom-combobox-toggle ui-corner-right" )
          .mousedown(function() {
            wasOpen = input.autocomplete( "widget" ).is( ":visible" );
          })
          .click(function() {
            input.focus();
 
            // Close if already visible
            if ( wasOpen ) {
              return;
            }
 
            // Pass empty string as value to search for, displaying all results
            input.autocomplete( "search", "" );
          });
      },
 
      _source: function( request, response ) {
        var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
        response( this.element.children( "option" ).map(function() {
          var text = $( this ).text();
          if ( this.value && ( !request.term || matcher.test(text) ) )
            return {
              label: text,
              value: text,
              option: this
            };
        }) );
      },
 
      _removeIfInvalid: function( event, ui ) {
 		
        // Selected an item, nothing to do
        if ( ui.item ) {
        	if (this.element.attr("id") == "catalogo_ctlg_valor_cdg"){
			     $.ajax({
							url: "<%= actualizar_controles_por_tipo_path %>",
							data: {
		  							tipo_control : this.element.val()
								  },
							dataType: "script"
				 });
        	}
          return;
        }
 
        // Search for a match (case-insensitive)
        var value = this.input.val(),
          valueLowerCase = value.toLowerCase(),
          valid = false;
        this.element.children( "option" ).each(function() {
          if ( $( this ).text().toLowerCase() === valueLowerCase ) {
            this.selected = valid = true;
            return false;
          }
        });
 
        // Found a match, nothing to do
        if ( valid ) {
        	if (this.element.attr("id") == "catalogo_ctlg_valor_cdg"){
			     $.ajax({
							url: "<%= actualizar_controles_por_tipo_path %>",
							data: {
		  							tipo_control : this.element.val()
								  },
							dataType: "script"
				 });
        	}
          return;
        }
 
        // Remove invalid value
        this.input
          .val( "" )
          .attr( "title", value + " no es una opción válida" )
          .tooltip( "open" );
        this.element.val( "" );
        this._delay(function() {
          this.input.tooltip( "close" ).attr( "title", "" );
        }, 2500 );
        this.input.data( "ui-autocomplete" ).term = "";
      },
 
      _destroy: function() {
        this.wrapper.remove();
        this.element.show();
      }
    });
  })( jQuery );
  </script>
<script>
   $(function() {
    $( "#funcion_control_modelo_id" ).combobox();
  });
  $(function() {
    $( "#funcion_control_accion_id" ).combobox();
  });
  $(function() {
    $( "#catalogo_ctlg_valor_cdg" ).combobox();
    
  });
  $(function() {
    $( "#funcion_control_control_id" ).combobox();
    
  });
  </script>

<%= form_for(@funcionalidad_funcion_control) do |f| %>
  <% if @funcionalidad_funcion_control.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionalidad_funcion_control.errors.count, "error", "errores") %> no permite(n) que este registro sea grabado: </h2>

      <ul>
      <% @funcionalidad_funcion_control.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="form_fields">
  		<div class="field">
    		<%= f.label :funcionalidad %><br>
    		<%= f.hidden_field :funcionalidad_id, value:@funcionalidad.id %>
    		<%= text_field_tag :descripcion, @funcionalidad.func_descripcion, size:100, disabled:true%>
  		</div>
  		<div class="field">
    		<%= f.label :modelo, "Modelo *" %><br>
    		<%= f.select :modelo_id, @modelos.map{|u| [u.mdl_nombre, u.id]}.insert(nil.to_f, nil) %>
  		</div>
  		<div class="field">
    		<%= f.label :accion, "Acción *" %><br>
    		<%= f.select :accion_id, @acciones.map{|u| [u.acc_nombre, u.id]}.insert(nil.to_f, nil) %>
  		</div>
  		<div class="field">
    		<%= f.label :tipo_control, "Tipo de control *" %><br>
    		<% if action_name == "new" then %>
    			<%= collection_select(:catalogo, :ctlg_valor_cdg, @tipos_control, :codigo, :descripcion, :prompt => '') %>
    		<% elsif action_name == "edit" %>
    			<%= collection_select(:catalogo, :ctlg_valor_cdg, @tipos_control, :codigo, :descripcion) %>
    		<% end %>
  		</div>
  		<div class="field">
    		<%= f.label :control, "Control *" %><br>
    		<% if action_name == "new" then %>
    			<%= f.select(:control_id, []) %>
    		<% elsif action_name == "edit" %>
    			<%= collection_select(:funcion_control, :control_id, @controles, :id, :ctrl_descripcion) %>
    		<% end %>
    		
  		</div>
  </div>
	<div class="bottom">
  		<div class="actions">
    		<% if action_name == "edit"%>
				<%= f.submit "Aceptar", class: "cmd save", id: :cmd_aceptar %> |
				<%= link_to 'Consultar', @funcionalidad, class: "cmd star", id: :cmd_consultar %> |
			<% elsif action_name == "new" or action_name =="create" %>
				<script>
					$(function(){
						$("#cmd_aceptar")
						.click(function(){
							$('#new_funcion_control').submit();
						});
					});
				</script>
				<%= link_to "Aceptar", nil, class: "cmd save", id: :cmd_aceptar %> |
			<% end %>
			<%= link_to 'Regresar', edit_funcionalidad_path(@funcionalidad), class: "cmd previous", id: :cmd_regresar %>
  		</div>
  	</div>
<% end %>

app/views/funcion_controls/actualizar_controles_por_tipo.js.erb
<% @controles = Control.select("id codigo, ctrl_descripcion descripcion").distinct.where("ctrl_tipo = '#{params[:tipo_control]}'").map{|a| [a.descripcion, a.codigo]}.insert(nil.to_f, nil) %>
$('#funcion_control_control_id').empty(); 
$('#funcion_control_control_id').html("<%= escape_javascript(options_for_select(@controles)) %>");

app/views/funcion_controls/edit.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Modificar control de funcionalidad</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	

app/views/funcion_controls/index.html.erb
<h1>Listing funcion_controls</h1>

<table>
  <thead>
    <tr>
      <th>Funcionalidad</th>
      <th>Modelo</th>
      <th>Accion</th>
      <th>Control</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @funcion_controls.each do |funcion_control| %>
      <tr>
        <td><%= funcion_control.funcionalidad %></td>
        <td><%= funcion_control.modelo %></td>
        <td><%= funcion_control.accion %></td>
        <td><%= funcion_control.control %></td>
        <td><%= link_to 'Show', funcion_control %></td>
        <td><%= link_to 'Edit', edit_funcion_control_path(funcion_control) %></td>
        <td><%= link_to 'Destroy', funcion_control, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funcion control', new_funcion_control_path, class: "cmd add", id: :cmd_crear %>

app/views/funcion_controls/new.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Nuevo control de funcionalidad</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	

app/views/funcion_controls/show.html.erb
<% if notice != nil then %>
	<div class="notibox success">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Funcionalidad - Control</h3>
			<div class="form">
				<div class = "form_fields">
					<table>
						<tbody>
							<tr>
								<td><strong>Funcionalidad</strong></td>
								<% funcionalidad = Funcionalidad.find(@funcion_control.funcionalidad_id) %>
							  	<td><%=funcionalidad.func_descripcion  %></td>
							</tr>
							<tr>
							  	<td><strong>Modelo</strong></td>
							  	<% modelo = Modelo.find(@funcion_control.modelo_id) %>
							  	<td><%= modelo.mdl_nombre %></td>
							</tr>
							<tr>
							  	<td><strong>Accion</strong></td>
							  	<% accion = Accion.find(@funcion_control.accion_id) %>
							  	<td><%= accion.acc_nombre %></td>
							</tr>
							<tr>
							  	<td><strong>Control</strong></td>
							  	<% control = Control.find(@funcion_control.control_id) %>
							  	<td><%= control.ctrl_descripcion %></td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="bottom">
					<%= link_to 'Editar', edit_funcionalidad_funcion_control_path(@funcionalidad, @funcion_control), class: "cmd edit", id: :cmd_editar %> |
					<%= link_to 'Regresar', edit_funcionalidad_path(@funcionalidad), class: "cmd previous", id: :cmd_regresar %>
				</div>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-