config/routes.rb
TravelApp::Application.routes.draw do  # The priority is based upon order of creation: first created -> highest priority.
  
  root 'dato_entidads#home'
  
  resources :regions
  resources :menus
  resources :accions
  resources :modelos
    
  resources :division_territorials
  resources :division_territorial_pais
  get 'entidad_territorials/actualizar_controles_dependientes' => 'entidad_territorials#actualizar_controles_dependientes', as: :actualizar_controles_dependientes
  
  concern :image_attachable do
    resources :fotos, only: :new
  end
  
  resources :paquete_turisticos, concerns: :image_attachable 
  resources :entidad_territorials, concerns: :image_attachable 
  
  
  
  resources :fotos
  
  resources :parametro_sistemas
  
  get 'dato_entidads/home' => 'dato_entidads#home', as: :home
  get 'dato_entidads/contactenos' => 'dato_entidads#contactenos'
  get 'dato_entidads/somos' => 'dato_entidads#somos'
  resources :dato_entidads
  
  
  resources :perfils do
    get '/perfils/:perlfil_id/permisos/new' => 'permisos#new'
    resources :permisos   
  end
  
  resources :permisos 
  
  resources :controls
  
  get 'funcion_controls/actualizar_controles_por_tipo' => 'funcion_controls#actualizar_controles_por_tipo', as: :actualizar_controles_por_tipo
  
  resources :funcion_controls
  
  resources :funcionalidads do
    resources :funcion_controls
  end
  
  get 'catalogos/actualizar_subcategorias' => 'catalogos#actualizar_subcategorias', as: :actualizar_subcategorias
  resources :catalogos
  
  
  get 'usuarios/cerrar_sesion' => 'usuarios#cerrar_sesion' , as: :cerrar_sesion
  get 'usuarios/iniciar_sesion' => 'usuarios#iniciar_sesion' , as: :iniciar_sesion
  post 'usuarios/change_password' => 'usuarios#change_password', as: :change_password
  get 'usuarios/new_password' => 'usuarios#new_password', as: :new_password
  get 'usuarios/login' => 'usuarios#login', as: :login
  post 'usuarios/login_attempt' => 'usuarios#login_attempt', as: :login_attempt
  resources :usuarios
  
    

  

end

app/models/division_territorial_pai.rb
class DivisionTerritorialPai < ActiveRecord::Base
  belongs_to :entidad_territorial
  belongs_to :division_territorial
end

app/controllers/division_territorial_pais_controller.rb
class DivisionTerritorialPaisController < ApplicationController
  
  include ApplicationHelper
  
  before_action :set_division_territorial_pai, only: [:show, :edit, :update, :destroy]
  before_action :set_datos_basicos, only: [:new, :create, :edit, :update]
  # GET /division_territorial_pais
  # GET /division_territorial_pais.json
  def index
    @division_territorial_pais = DivisionTerritorialPai.all
  end

  # GET /division_territorial_pais/1
  # GET /division_territorial_pais/1.json
  def show
  end

  # GET /division_territorial_pais/new
  def new
    @division_territorial_pai = DivisionTerritorialPai.new
  end

  # GET /division_territorial_pais/1/edit
  def edit
  end

  # POST /division_territorial_pais
  # POST /division_territorial_pais.json
  def create
    @division_territorial_pai = DivisionTerritorialPai.new(division_territorial_pai_params)

    respond_to do |format|
      if @division_territorial_pai.save
        format.html { redirect_to @division_territorial_pai, notice: 'Division territorial creada exitosamente.' }
        format.json { render action: 'show', status: :created, location: @division_territorial_pai }
      else
        format.html { render action: 'new' }
        format.json { render json: @division_territorial_pai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /division_territorial_pais/1
  # PATCH/PUT /division_territorial_pais/1.json
  def update
    
    respond_to do |format|
      if @division_territorial_pai.update(division_territorial_pai_params)
        format.html { redirect_to @division_territorial_pai, notice: 'Division territorial actualizada exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @division_territorial_pai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /division_territorial_pais/1
  # DELETE /division_territorial_pais/1.json
  def destroy
    @division_territorial_pai.destroy
    respond_to do |format|
      format.html { redirect_to division_territorial_pais_url }
      format.json { head :no_content }
    end
  end

    def set_estado_registro_actual
      if action_name == "new" then
        @estado_registro = "A"
      elsif action_name == "show" then
        catalogo = Catalogo.find_by ctlg_categoria: 'ESTADO REGISTRO', ctlg_valor_cdg: @division_territorial_pai.dte_estado_registro
        @estado_registro = catalogo.ctlg_valor_desc
      elsif action_name == "edit" then
        catalogo = Catalogo.find_by ctlg_categoria: 'ESTADO REGISTRO', ctlg_valor_cdg: @division_territorial_pai.dte_estado_registro
        @estado_registro = catalogo.ctlg_valor_cdg
      end
    end


  private
  
    def set_datos_basicos 
      set_estados_registro # todos los estados de un registro
      set_estado_registro_actual
      set_paises
      @divisionesTerritoriales = DivisionTerritorial.where("dvt_estado_registro = 'A'")
      @continentes = EntidadTerritorial.where("enter_padre = 1")
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_division_territorial_pai
      @division_territorial_pai = DivisionTerritorialPai.find(params[:id])
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def division_territorial_pai_params
      params.require(:division_territorial_pai).permit(:entidad_territorial_id, :division_territorial_id, :dte_nivel, :dte_estado_registro)
    end
end

app/helpers/division_territorial_pais_helper.rb
module DivisionTerritorialPaisHelper
end

app/views/division_territorial_pais/_form.html.erb
<style>
  .custom-combobox {
    position: relative;
    display: inline-block;
  }
  .custom-combobox-toggle {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-left: -1px;
    padding: 0;
    /* support: IE7 */
    *height: 1.7em;
    *top: 0.1em;
  }
  .custom-combobox-input {
    margin: 0;
    padding: 0.3em;
  }
  </style>
  <script>
  (function( $ ) {
    $.widget( "custom.combobox", {
      _create: function() {
        this.wrapper = $( "<span>" )
          .addClass( "custom-combobox" )
          .insertAfter( this.element );
 
        this.element.hide();
        this._createAutocomplete();
        this._createShowAllButton();
      },
 
      _createAutocomplete: function() {
        var selected = this.element.children( ":selected" ),
          value = selected.val() ? selected.text() : "";
 
        this.input = $( "<input>" )
          .appendTo( this.wrapper )
          .val( value )
          .attr( "title", "" )
          .addClass( "custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left" )
          .autocomplete({
            delay: 0,
            minLength: 0,
            source: $.proxy( this, "_source" )
          })
          .tooltip({
            tooltipClass: "ui-state-highlight"
          });
 
        this._on( this.input, {
          autocompleteselect: function( event, ui ) {
            ui.item.option.selected = true;
            this._trigger( "select", event, {
              item: ui.item.option
            });
          },
 
          autocompletechange: "_removeIfInvalid"
        });
      },
 
      _createShowAllButton: function() {
        var input = this.input,
          wasOpen = false;
 
        $( "<a>" )
          .attr( "tabIndex", -1 )
          //.attr( "title", "Mostrar todas las opciones" )
          .tooltip()
          .appendTo( this.wrapper )
          .button({
            icons: {
              primary: "ui-icon-triangle-1-s"
            },
            text: false
          })
          .removeClass( "ui-corner-all" )
          .addClass( "custom-combobox-toggle ui-corner-right" )
          .mousedown(function() {
            wasOpen = input.autocomplete( "widget" ).is( ":visible" );
          })
          .click(function() {
            input.focus();
 
            // Close if already visible
            if ( wasOpen ) {
              return;
            }
 
            // Pass empty string as value to search for, displaying all results
            input.autocomplete( "search", "" );
          });
      },
 
      _source: function( request, response ) {
        var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
        response( this.element.children( "option" ).map(function() {
          var text = $( this ).text();
          if ( this.value && ( !request.term || matcher.test(text) ) )
            return {
              label: text,
              value: text,
              option: this
            };
        }) );
      },
 
      _removeIfInvalid: function( event, ui ) {
 
        // Selected an item, nothing to do
        if ( ui.item ) {
        	if (this.element.attr('id') == 1 || this.element.attr('id') == 2){
				$.ajax({
					url: "<%= actualizar_controles_dependientes_path %>",
					data: {
							enter_padre_id: this.element.val(),
							control_id: (eval(this.element.attr('id')) + 1),
					  	},
					dataType: "script"
	 			});
	 			
	 			$("#division_territorial_pai_entidad_territorial_id").val(this.element.val());
	 		}
          return;
        }
 
        // Search for a match (case-insensitive)
        var value = this.input.val(),
          valueLowerCase = value.toLowerCase(),
          valid = false;
        this.element.children( "option" ).each(function() {
          if ( $( this ).text().toLowerCase() === valueLowerCase ) {
            this.selected = valid = true;
            return false;
          }
        });
 
        // Found a match, nothing to do
        if ( valid ) {
        	if (this.element.attr('id') == 1 || this.element.attr('id') == 2){
				$.ajax({
					url: "<%= actualizar_controles_dependientes_path %>",
					data: {
							enter_padre_id: this.element.val(),
							control_id: (eval(this.element.attr('id')) + 1),
					  	},
					dataType: "script"
	 			});
	 			
	 			$("#division_territorial_pai_entidad_territorial_id").val(this.element.val());
	 		}        	
          return;
        }
 
        // Remove invalid value
        this.input
          .val( "" )
          .attr( "title", value + " no es una opción válida" )
          .tooltip( "open" );
        this.element.val( "" );
        this._delay(function() {
          this.input.tooltip( "close" ).attr( "title", "" );
        }, 2500 );
        this.input.data( "ui-autocomplete" ).term = "";
      },
 
      _destroy: function() {
        this.wrapper.remove();
        this.element.show();
      }
    });
  })( jQuery );
  </script>
<script>
   $(function() {
    $( "#1" ).combobox();
    $( "#toggle" ).click(function() {
      $( "#1" ).toggle();
    });
  });
   $(function() {
    $( "#2" ).combobox();
    $( "#toggle" ).click(function() {
      $( "#2" ).toggle();
    });
  });
  $(function() {
    $( "#division_territorial_pai_division_territorial_id" ).combobox();
    $( "#toggle" ).click(function() {
      $( "#division_territorial_pai_division_territorial_id" ).toggle();
    });
  });
  $(function() {
    $( "#division_territorial_pai_dte_estado_registro" ).combobox();
    $( "#toggle" ).click(function() {
      $( "#division_territorial_pai_dte_estado_registro" ).toggle();
    });
  });
  </script>  
<%= form_for(@division_territorial_pai) do |f| %>
	<% if @division_territorial_pai.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@division_territorial_pai.errors.count, "error", "errores") %> no permite(n) que este registro sea grabado: </h2>
      		<ul>
      			<% @division_territorial_pai.errors.full_messages.each do |msg| %>
        			<li><%= msg %></li>
      			<% end %>
      		</ul>
    	</div>
  	<% end %>
	<div class="form_fields">
	  	<div class="field">
	    	<%= f.label :entidad_territorial, "Entidad territorial *" %><br>
	    	<%= f.hidden_field :entidad_territorial_id %>
	    	<%= select_tag "1", options_from_collection_for_select(@continentes, "id", "enter_nombre_oficial"), prompt: ""  %>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= select_tag "2", nil  %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :division_territorial, "Unidad político-administrativa *" %><br>
	    	<%= f.select :division_territorial_id, @divisionesTerritoriales.map{|t| [t.dvt_nombre, t.id]}.insert(nil.to_f,nil) %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :dte_nivel , "Nivel *"%><br>
	    	<%= f.number_field :dte_nivel %>
	  	</div>
	  	<div class="field">
	    	<%= f.label :dte_estado_registro, "Estado registro *" %><br>
	    	<%= f.select :dte_estado_registro , @estados_registro.map{|u| [u.ctlg_valor_desc, u.ctlg_valor_cdg]}.insert(nil.to_f, nil), selected: @estado_registro %>
	  	</div>
	</div>
  	<div class="bottom">
  		<div class="actions">
    		<% if action_name == "edit"%>
				<%= f.submit "Aceptar", class: "cmd save", id: :cmd_aceptar %> |
				<%= link_to 'Consultar', @division_territorial_pai, class: "cmd star", id: :cmd_consultar %> |
			<% elsif action_name == "new" or action_name =="create" %>
				<script>
					$(function(){
						$("#cmd_aceptar")
						.click(function(){
							$('#new_division_territorial_pai').submit();
						});
					});
				</script>	
				<%= link_to "Aceptar", nil, class: "cmd save", id: :cmd_aceptar %> |
			<% end %>
			<%= link_to 'Regresar', division_territorial_pais_path, class: "cmd previous", id: :cmd_regresar %>
  		</div>
  	</div>
	
<% end %>

app/views/division_territorial_pais/edit.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Modificar divisi&oacute;n territorial pa&iacute;s</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-->

app/views/division_territorial_pais/index.html.erb
<script>
$(document).ready(function() {
    $('#table_index').dataTable( {
    	"bJQueryUI": true,
        "sPaginationType": "full_numbers"
    } );
} );
</script>

<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Divisiones territoriales</h3>
			<center>
				<br/>
				<table id="table_index">
				  <thead>
				    <tr>
				      <th>Entidad territorial</th>
				      <th>Division territorial</th>
				      <th>Nivel</th>
				      <th>Estado registro</th>
				      <th></th>
			      	  <th></th>
				    </tr>
				  </thead>
				
				  <tbody>
				    <% @division_territorial_pais.each do |div_terr_pais| %>
				      <tr>
				        <td><%= div_terr_pais.entidad_territorial.enter_nombre_oficial %></td>
				        <td><%= link_to div_terr_pais.division_territorial.dvt_nombre, div_terr_pais %></td>
				        <td><%= div_terr_pais.dte_nivel %></td>
				        <td><%= div_terr_pais.dte_estado_registro %></td>
				        <td><%= link_to 'Editar', edit_division_territorial_pai_path(div_terr_pais), class: "cmd edit" %></td>
				        <td><%= link_to 'Borrar', div_terr_pais, method: :delete, data: { confirm: '¿Está seguro de eliminar este registro?' }, class: "cmd delete" %></td>
				      </tr>
				    <% end %>
				  </tbody>
  				</table>
			</center>
			<div class="bottom">
				<%= link_to 'Crear division territorial', new_division_territorial_pai_path, class: "cmd add", id: :cmd_crear %>
			</div>
		</div>
	</div>
</div>

app/views/division_territorial_pais/new.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Nueva divisi&oacute;n territorial pa&iacute;s</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-->

app/views/division_territorial_pais/show.html.erb
<% if notice != nil then %>
	<div class="notibox success">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>

<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Divisi&oacute;n Territorial Pa&iacute;s</h3>
			<div class="form">
				<div class = "form_fields">
					<table>
						<tbody>
							<tr>
							  <td><strong>Pa&iacute;s:</strong></td>
							  <td><%= @division_territorial_pai.entidad_territorial.enter_nombre_oficial %></td>
							</tr>
							
							<tr>
							  <td><strong>Division territorial:</strong></td>
							  <td><%= @division_territorial_pai.division_territorial.dvt_nombre %></td>
							</tr>
							
							<tr>
							  <td><strong>Nivel:</strong></td>
							  <td><%= @division_territorial_pai.dte_nivel %></td>
							</tr>
							
							<tr>
							  <td><strong>Estado registro:</strong></td>
							  <td><%= @division_territorial_pai.dte_estado_registro %></td>
							</tr>
						</tbody>
					</table>
				</div>
					
			<div class="bottom">
				<%= link_to 'Editar', edit_division_territorial_pai_path(@division_territorial_pai), class: "cmd edit", id: :cmd_editar %> |
				<%= link_to 'Regresar', division_territorial_pais_path, class:"cmd previous", id: :cmd_regresar %>
			</div>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-->