config/routes.rb
TravelApp::Application.routes.draw do  # The priority is based upon order of creation: first created -> highest priority.
  
  root 'dato_entidads#home'
  
  resources :regions
  resources :menus
  resources :accions
  resources :modelos
    
  resources :division_territorials
  resources :division_territorial_pais
  get 'entidad_territorials/actualizar_controles_dependientes' => 'entidad_territorials#actualizar_controles_dependientes', as: :actualizar_controles_dependientes
  
  concern :image_attachable do
    resources :fotos, only: :new
  end
  
  resources :paquete_turisticos, concerns: :image_attachable 
  resources :entidad_territorials, concerns: :image_attachable 
  
  
  
  resources :fotos
  
  resources :parametro_sistemas
  
  get 'dato_entidads/home' => 'dato_entidads#home', as: :home
  get 'dato_entidads/contactenos' => 'dato_entidads#contactenos'
  get 'dato_entidads/somos' => 'dato_entidads#somos'
  resources :dato_entidads
  
  
  resources :perfils do
    get '/perfils/:perlfil_id/permisos/new' => 'permisos#new'
    resources :permisos   
  end
  
  resources :permisos 
  
  resources :controls
  
  get 'funcion_controls/actualizar_controles_por_tipo' => 'funcion_controls#actualizar_controles_por_tipo', as: :actualizar_controles_por_tipo
  
  resources :funcion_controls
  
  resources :funcionalidads do
    resources :funcion_controls
  end
  
  get 'catalogos/actualizar_subcategorias' => 'catalogos#actualizar_subcategorias', as: :actualizar_subcategorias
  resources :catalogos
  
  
  get 'usuarios/cerrar_sesion' => 'usuarios#cerrar_sesion' , as: :cerrar_sesion
  get 'usuarios/iniciar_sesion' => 'usuarios#iniciar_sesion' , as: :iniciar_sesion
  post 'usuarios/change_password' => 'usuarios#change_password', as: :change_password
  get 'usuarios/new_password' => 'usuarios#new_password', as: :new_password
  get 'usuarios/login' => 'usuarios#login', as: :login
  post 'usuarios/login_attempt' => 'usuarios#login_attempt', as: :login_attempt
  resources :usuarios
  
    

  

end

app/models/funcionalidad.rb
class Funcionalidad < ActiveRecord::Base
end

app/controllers/funcionalidads_controller.rb
class FuncionalidadsController < ApplicationController
  before_action :set_funcionalidad, only: [:show, :edit, :update, :destroy]

  # GET /funcionalidads
  # GET /funcionalidads.json
  def index
    @funcionalidads = Funcionalidad.all
  end

  # GET /funcionalidads/1
  # GET /funcionalidads/1.json
  def show
    @funcionControls = FuncionControl.where("funcionalidad_id = #{@funcionalidad.id}")
  end

  # GET /funcionalidads/new
  def new
    @funcionalidad = Funcionalidad.new
  end

  # GET /funcionalidads/1/edit
  def edit
    @funcionControls = FuncionControl.where("funcionalidad_id = #{@funcionalidad.id}")
  end

  # POST /funcionalidads
  # POST /funcionalidads.json
  def create
    @funcionalidad = Funcionalidad.new(funcionalidad_params)

    respond_to do |format|
      if @funcionalidad.save
        format.html { redirect_to @funcionalidad, notice: 'Funcionalidad creada exitosamente.' }
        format.json { render action: 'show', status: :created, location: @funcionalidad }
      else
        format.html { render action: 'new' }
        format.json { render json: @funcionalidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionalidads/1
  # PATCH/PUT /funcionalidads/1.json
  def update
    respond_to do |format|
      if @funcionalidad.update(funcionalidad_params)
        format.html { redirect_to @funcionalidad, notice: 'Funcionalidad actualizada exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @funcionalidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionalidads/1
  # DELETE /funcionalidads/1.json
  def destroy
    @funcionalidad.destroy
    respond_to do |format|
      format.html { redirect_to funcionalidads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionalidad
      @funcionalidad = Funcionalidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionalidad_params
      params.require(:funcionalidad).permit(:func_descripcion, :func_publica, :func_padre)
    end
end

app/helpers/funcionalidads_helper.rb
module FuncionalidadsHelper
end

app/views/funcionalidads/_form.html.erb
<style>
	td{
		color:#000000;
	}
</style>
<%= form_for(@funcionalidad) do |f| %>
  	<% if @funcionalidad.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@funcionalidad.errors.count, "error", "errores") %> no permite(n) que este registro sea grabado: </h2>
      		<ul>
      			<% @funcionalidad.errors.full_messages.each do |msg| %>
        			<li><%= msg %></li>
      			<% end %>
      		</ul>
    	</div>
  	<% end %>
  	
	<div class="form_fields">
  		<div class="field">
    		<%= f.label :Descripción, "Descripción *" %><br>
    		<%= f.text_field :func_descripcion, options= {size: 100, maxlength: 100, required: :required, "data-validation" => "length alphanumeric", "data-validation-allowing" => " ", "data-validation-length" => "min5"} %>
  		</div>
  		<div class="field">
    		<%= f.label :Pública, "Pública *" %><br>
    		<%= f.select :func_publica, [['NO', 'N'], ['SI','S']] %>
  		</div>
  		<!-- <div class="field">
    		<%= f.label :Padre %><br>
    		<%= f.number_field :func_padre %>
  		</div> -->
  		<% if action_name == "edit" %>
			<script>
				$(document).ready(function() {
					$('#table_index').dataTable( {
						"bJQueryUI": true,
	    				"sPaginationType": "full_numbers"
					} );
				} );
			</script>
			<center>
					<table id="table_index">
					<thead>
						<tr>
	  						<th>Modelo</th>
	  						<th>Acci&oacute;n</th>
	  						<th>Control</th>
	  						<th></th>
	  						<th></th>
						</tr>
					</thead>
					<tbody>
						<% @funcionControls.each do |fctrl| %>
	  						<tr>
	    						<% modelo = Modelo.find(fctrl.modelo_id) %>
	    						<td><%= modelo.mdl_nombre %></td>
	    						<% accion = Accion.find(fctrl.accion_id)%>
	    						<td><%= accion.acc_nombre %></td>
	    						<% control = Control.find(fctrl.control_id)%>
	    						<%catalogo = Catalogo.find_by ctlg_valor_cdg: control.ctrl_tipo %>
	  							<%tipoControl = catalogo.ctlg_valor_desc %>
	    						<td><%= tipoControl + " " + control.ctrl_descripcion %></td>
	    						<td><%= link_to 'Editar', edit_funcionalidad_funcion_control_path(@funcionalidad, fctrl), class: "cmd edit", id: :cmd_editar %></td>
	    						<td><%= link_to 'Borrar', fctrl, method: :delete, data: { confirm: '¿Está seguro de eliminar este registro?' }, class:"cmd delete", id: :cmd_borrar %></td>
	  						</tr>
						<% end %>
					</tbody>
				</table>
			</center>
			<div class="bottom">
				<%= link_to 'Crear objeto', new_funcionalidad_funcion_control_path(@funcionalidad), class: "cmd add", id: :cmd_crear %>
			</div>
	<% end %>
  		
	</div>
  	

  	
	<div class="bottom">
  		<div class="actions">
    		<% if action_name == "edit"%>
				<%= f.submit "Aceptar", class: "cmd save", id: :cmd_aceptar %> |
				<%= link_to 'Consultar', @funcionalidad, class: "cmd star", id: :cmd_consultar %> |
			<% elsif action_name == "new" or action_name =="create" %>
				<script>
					$(function(){
						$("#cmd_aceptar")
						.click(function(){
							$('#new_funcionalidad').submit();
						});
					});
				</script>
				<%= link_to "Aceptar", nil, class: "cmd save", id: :cmd_aceptar %> |
			<% end %>
			<%= link_to 'Regresar', funcionalidads_url, class: "cmd previous", id: :cmd_regresar %>
  		</div>
  	</div>
<% end %>
<script>$.validate();</script>

app/views/funcionalidads/edit.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Modificar funcionalidad</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	

app/views/funcionalidads/index.html.erb
<style>
	  table.dataTable tbody td:nth-child(1){
  width:60%;
  }
    table.dataTable tbody td:nth-child(2){
  width:10%;
  }
    table.dataTable tbody td:nth-child(3){
  width:15%;
  }
    table.dataTable tbody td:nth-child(4){
  width:15%;
  }
</style>
<script>
$(document).ready(function() {
    $('#table_index').dataTable( {
    	"bJQueryUI": true,
        "sPaginationType": "full_numbers"
    } );
} );
</script>

<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Funcionalidades</h3>
			<center>
				<br/>
				<table id="table_index">
  					<thead>
    					<tr>
      						<th>Descripci&oacute;n</th>
      						<th>P&uacute;blica</th>
      						<th></th>
      						<th></th>
   						</tr>
  					</thead>
  					<tbody>
    					<% @funcionalidads.each do |funcionalidad| %>
      						<tr>
        						<td><%= link_to funcionalidad.func_descripcion, funcionalidad %></td>
        						<%if funcionalidad.func_publica == "S" then %>
        							<td>SI</td>
        						<% else %>
        							<td>NO</td>
        						<% end %>
        						
        						<td><%= link_to 'Editar', edit_funcionalidad_path(funcionalidad), class: "cmd edit", id: :cmd_editar %></td>
        						<td><%= link_to 'Borrar', funcionalidad, method: :delete, data: { confirm: '¿Está seguro de eliminar este registro?' }, class:"cmd delete", id: :cmd_borrar %></td>
      						</tr>
    					<% end %>
  					</tbody>
				</table>

				<br>
			</center>
			<div class="bottom">
				<%= link_to 'Crear funcionalidad', new_funcionalidad_path, class: "cmd add", id: :cmd_crear %>
			</div>
		</div>
	</div>
</div>

app/views/funcionalidads/new.html.erb
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Nueva funcionalidad</h3>
			<%= render 'form' %>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	

app/views/funcionalidads/show.html.erb
<script>
$(document).ready(function() {
    $('#table_index').dataTable( {
    	"bJQueryUI": true,
        "sPaginationType": "full_numbers"
    } );
} );
</script>

<% if notice != nil then %>
	<div class="notibox success">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>
<div class="wrapper">
	<div class="content">
		<div class="form_wrapper">
			<h3>Funcionalidad</h3>
			<div class="form">
				<div class = "form_fields">
					<table>
						<tbody>
							<tr>
						  		<td><strong>Descripci&oacute;n:</strong></td>
						  		<td><%= @funcionalidad.func_descripcion %></td>
							</tr>
							<tr>
						  		<td><strong>P&uacute;blica?</strong></td>
						  		<td><%= @funcionalidad.func_publica %></td>
							</tr>
						</tbody>
					</table>
					<br/>
					<table id="table_index">
						<thead>
							<tr>
	  							<th>Modelo</th>
	  							<th>Acci&oacute;n</th>
	  							<th>Control</th>
							</tr>
						</thead>
						<tbody>
							<% @funcionControls.each do |fctrl| %>
		  						<tr>
		    						<% modelo = Modelo.find(fctrl.modelo_id) %>
		    						<td><%= modelo.mdl_nombre %></td>
		    						<% accion = Accion.find(fctrl.accion_id)%>
		    						<td><%= accion.acc_nombre %></td>
		    						<% control = Control.find(fctrl.control_id)%>
		    						<%catalogo = Catalogo.find_by ctlg_valor_cdg: control.ctrl_tipo %>
		  							<%tipoControl = catalogo.ctlg_valor_desc %>
		    						<td><%= tipoControl + " " + control.ctrl_descripcion %></td>
		  						</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				<div class="bottom">
					<%= link_to 'Editar', edit_funcionalidad_path(@funcionalidad), class: "cmd edit", id: :cmd_editar %>  |
					<%= link_to 'Regresar', funcionalidads_path, class: "cmd previous", id: :cmd_regresar %>
				</div>
		</div><!--form_wrapper-->
	</div><!--content-->
</div><!--wrapper-	